// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PackingTool.Database.DbModels
{
    public partial class PackingList
    {
        public PackingList()
        {
            UserPackingList = new HashSet<UserPackingList>();
        }

        public int PackingListId { get; set; }
        public string Name { get; set; }
        public string Json { get; set; }
        public bool Deleted { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
        public DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }

        public virtual ICollection<UserPackingList> UserPackingList { get; set; }
    }
}