// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PackingTool.Database.DbModels.DbModels
{
    public partial class User
    {
        public User()
        {
            UserPackingList = new HashSet<UserPackingList>();
        }

        public int UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
        public DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }

        public virtual ICollection<UserPackingList> UserPackingList { get; set; }
    }
}