// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PackingTool.Database.DbModels.DbModels
{
    public partial class UserPackingList
    {
        public int UserPackingListId { get; set; }
        public int UserId { get; set; }
        public int PackingListId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }

        public virtual PackingList PackingList { get; set; }
        public virtual User User { get; set; }
    }
}